-- COMPREHENSIVE DB SETUP FOR INSTAGRAM SCRAPER
-- Run these in your Supabase SQL Editor

-- 1. Create Unified Trends Table
CREATE TABLE IF NOT EXISTS trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    platform TEXT DEFAULT 'Instagram'::text,
    topic_hashtag TEXT NOT NULL,
    url TEXT,
    likes BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    shares BIGINT DEFAULT 0,
    views BIGINT DEFAULT 0,
    engagement_score DOUBLE PRECISION DEFAULT 0.0,
    sentiment_polarity DOUBLE PRECISION,
    sentiment_label TEXT,
    category TEXT,
    language TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    posts JSONB DEFAULT '[]'::jsonb,
    version_id UUID,
    scraped_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_trends_topic_hashtag ON trends(topic_hashtag);
CREATE INDEX IF NOT EXISTS idx_trends_scraped_at ON trends(scraped_at DESC);
CREATE INDEX IF NOT EXISTS idx_trends_engagement_score ON trends(engagement_score DESC);

-- 2. Create Scraper Runs Table
CREATE TABLE IF NOT EXISTS scraper_runs (
    id BIGSERIAL PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'running',
    hashtags_discovered INTEGER DEFAULT 0,
    hashtags_saved INTEGER DEFAULT 0,
    new_records INTEGER DEFAULT 0,
    updated_records INTEGER DEFAULT 0,
    error_message TEXT,
    error_type VARCHAR(100),
    version_id VARCHAR(100),
    proxy_used VARCHAR(255),
    proxy_pool_size INTEGER,
    config_snapshot JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Scraper Logs Table
CREATE TABLE IF NOT EXISTS scraper_logs (
    id BIGSERIAL PRIMARY KEY,
    run_id BIGINT REFERENCES scraper_runs(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    level VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    step VARCHAR(100),
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Enable RLS (if needed) or just verify access
-- Ensure your Supabase Key has permissions to these tables.
