-- Normalized Schema for Instagram Scraper (Sprint-1 Revision)
-- This schema supports the ETLPipeline for multi-platform trend analysis

-- 1. Trends Table (Core Trend Identity)
CREATE TABLE IF NOT EXISTS trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    url TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Hashtags Table (Unique Hashtag Metadata)
CREATE TABLE IF NOT EXISTS hashtags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Trend-Hashtag Link (Many-to-Many relationship)
CREATE TABLE IF NOT EXISTS trend_hashtags (
    trend_id BIGINT REFERENCES trends(id) ON DELETE CASCADE,
    hashtag_id BIGINT REFERENCES hashtags(id) ON DELETE CASCADE,
    is_primary BOOLEAN DEFAULT false,
    PRIMARY KEY (trend_id, hashtag_id)
);

-- 4. Engagement Metrics (Historical Engagement Tracking)
CREATE TABLE IF NOT EXISTS engagement_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_id BIGINT REFERENCES trends(id) ON DELETE CASCADE,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    likes BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    views BIGINT DEFAULT 0,
    shares BIGINT DEFAULT 0,
    reactions BIGINT DEFAULT 0,
    engagement_score DOUBLE PRECISION DEFAULT 0.0,
    language TEXT,
    version_id UUID,
    
    -- Analysis data
    sentiment_polarity DOUBLE PRECISION,
    sentiment_label TEXT
);

-- 5. Snapshots (Full Scraper Run Audit Trail)
CREATE TABLE IF NOT EXISTS snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_id BIGINT REFERENCES trends(id) ON DELETE CASCADE,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    version_id UUID,
    raw_data JSONB NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_engagement_metrics_trend_id ON engagement_metrics(trend_id);
CREATE INDEX IF NOT EXISTS idx_engagement_metrics_recorded_at ON engagement_metrics(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_hashtags_name ON hashtags(name);
CREATE INDEX IF NOT EXISTS idx_trends_url ON trends(url);
CREATE INDEX IF NOT EXISTS idx_snapshots_version_id ON snapshots(version_id);
