-- Schema for Instagram Scraper (Current Contract)
-- Matches 'instagram' table usage in main.py

CREATE TABLE IF NOT EXISTS trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Core Fields
    platform TEXT DEFAULT 'Instagram'::text,
    topic_hashtag TEXT NOT NULL,
    url TEXT,
    
    -- Engagement Metrics
    likes BIGINT DEFAULT 0,
    comments BIGINT DEFAULT 0,
    shares BIGINT DEFAULT 0,
    views BIGINT DEFAULT 0,
    engagement_score DOUBLE PRECISION DEFAULT 0.0,
    
    -- Sentiment
    sentiment_polarity DOUBLE PRECISION,
    sentiment_label TEXT,
    
    -- Metadata & Analysis
    category TEXT,
    language TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,  -- Stores format, content_types, etc.
    posts JSONB DEFAULT '[]'::jsonb,     -- Stores top posts data
    
    -- Versioning
    version_id UUID,
    scraped_at TIMESTAMP WITH TIME ZONE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_trends_topic_hashtag ON trends(topic_hashtag);
CREATE INDEX IF NOT EXISTS idx_trends_scraped_at ON trends(scraped_at DESC);
CREATE INDEX IF NOT EXISTS idx_trends_engagement_score ON trends(engagement_score DESC);

-- Snapshots Table: Stores daily snapshots of trend data
CREATE TABLE IF NOT EXISTS trend_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_id TEXT NOT NULL,
    snapshot_date TIMESTAMP WITH TIME ZONE NOT NULL,
    version_id UUID,
    
    -- Trend Data
    platform TEXT,
    hashtag TEXT,
    engagement_score DOUBLE PRECISION,
    likes BIGINT,
    comments BIGINT,
    shares BIGINT,
    views BIGINT,
    
    -- Analysis
    language TEXT,
    sentiment_polarity DOUBLE PRECISION,
    sentiment_label TEXT,
    posts_count INTEGER,
    rank INTEGER,
    
    -- JSON Data
    change_from_previous JSONB,
    metadata JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Unique constraint for daily snapshots per trend
    UNIQUE(trend_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_trend_snapshots_trend_id ON trend_snapshots(trend_id);
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_snapshot_date ON trend_snapshots(snapshot_date DESC);
