-- Snapshots Table: Stores daily snapshots of trend data for historical analysis
CREATE TABLE IF NOT EXISTS trend_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_id TEXT NOT NULL,
    snapshot_date TIMESTAMP WITH TIME ZONE NOT NULL,
    version_id UUID,
    
    -- Trend Data
    platform TEXT,
    hashtag TEXT,
    engagement_score DOUBLE PRECISION,
    likes BIGINT,
    comments BIGINT,
    shares BIGINT,
    views BIGINT,
    
    -- Analysis
    language TEXT,
    sentiment_polarity DOUBLE PRECISION,
    sentiment_label TEXT,
    posts_count INTEGER,
    rank INTEGER,
    
    -- JSON Data
    change_from_previous JSONB,
    metadata JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Unique constraint for daily snapshots per trend
    UNIQUE(trend_id, snapshot_date)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_trend_id ON trend_snapshots(trend_id);
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_snapshot_date ON trend_snapshots(snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_trend_snapshots_platform ON trend_snapshots(platform);
