"""
Helper script to create .env file for Supabase configuration.
Run this script to interactively set up your .env file.
"""

import os
import sys

# Fix encoding for Windows console
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

def create_env_file():
    """Create .env file with Supabase credentials."""
    env_path = ".env"
    
    # Check if .env already exists
    if os.path.exists(env_path):
        response = input(f"\n⚠️  .env file already exists. Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("❌ Cancelled. Existing .env file preserved.")
            return
    
    print("\n" + "="*60)
    print("🔧 Supabase Configuration Setup")
    print("="*60)
    print("\nYou can find your Supabase credentials in your Supabase dashboard:")
    print("  1. Go to https://supabase.com and sign in")
    print("  2. Select your project")
    print("  3. Go to Settings > API")
    print("  4. Copy your 'Project URL' and 'anon public' key")
    print("\n" + "-"*60)
    
    # Get Supabase URL
    supabase_url = input("\n📝 Enter your Supabase Project URL: ").strip()
    if not supabase_url:
        print("❌ Supabase URL is required. Exiting.")
        return
    
    # Validate URL format
    if not supabase_url.startswith("https://"):
        print("⚠️  Warning: URL should start with https://")
        if not supabase_url.startswith("http://"):
            supabase_url = "https://" + supabase_url
    
    # Get Supabase Key
    supabase_key = input("📝 Enter your Supabase anon public key: ").strip()
    if not supabase_key:
        print("❌ Supabase key is required. Exiting.")
        return
    
    # Create .env file content
    env_content = f"""# Supabase Configuration
# Generated by setup_env.py

SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}
"""
    
    # Write to file
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        print(f"\n✅ Successfully created .env file!")
        print(f"📁 Location: {os.path.abspath(env_path)}")
        print("\n🔒 Security Note: The .env file contains sensitive credentials.")
        print("   Make sure it's in your .gitignore file and never commit it to version control.")
        print("\n✅ You can now run: python t3_scraper.py")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")

if __name__ == "__main__":
    create_env_file()

